### ISSUE TITLE
Cover status doesn't update

### ISSUE THREAD

**Issue by patienttruth** [andyrak/hacs-aladdin-legacy#32]
### ## System Information

version | core-2024.5.2
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.12.2
os_name | Linux
os_version | 6.6.29-haos
arch | x86_64
timezone | America/Los_Angeles
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 4976
Installed Version | 1.34.0
Stage | running
Available Repositories | 1402
Downloaded Repositories | 45
HACS Data | ok

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 12.3
-- | --
update_channel | stable
supervisor_version | supervisor-2024.05.1
agent_version | 1.6.0
docker_version | 25.0.5
disk_total | 30.8 GB
disk_used | 23.6 GB
healthy | true
supported | true
board | ova
supervisor_api | ok
version_api | ok
installed_addons | Bookstack (2.0.5), Let's Encrypt (5.0.15), File editor (5.8.0), Advanced SSH & Web Terminal (17.3.0), motionEye (0.20.0), Piper (1.5.0), Grocy (0.21.0), Terminal & SSH (9.14.0), Whisper (2.0.0), openWakeWord (1.10.0), Music Assistant BETA (2.1.0b0), MariaDB (2.7.1), Traccar (0.25.0), go2rtc (1.9.2), Studio Code Server (5.15.0), Frigate Proxy (1.5), ESPHome (2024.5.0), Log Viewer (0.17.0)

</details>

<details><summary>Dashboards</summary>

dashboards | 9
-- | --
resources | 20
views | 34
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | May 9, 2024 at 01:16
-- | --
current_recorder_run | May 18, 2024 at 09:32
estimated_db_size | 360.55 MiB
database_engine | sqlite
database_version | 3.44.2

</details>

### Checklist

- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of any [previous issues](https://github.com/andyrak/hacs-aladdin-legacy/issues?q=is%3Aissue+label%3A%22Bug%22+)..

### Describe the issue

Cover status is not immediately updated when status changes due to outside action. i.e. manual button in garage or Genie app.

Earlier this week errors were generated in the log because the Genie API responded with "already open" or something similar.

Here's an example error log I just caused:
<details><summary>error log</summary

```
2024-05-18 14:21:24.510 ERROR (MainThread) [custom_components.aladdin_connect] [API] An error occurred sending command OPEN_DOOR to door Far Garage Door; {"error":"Device is offline","type":"BusinessLogicError"}
2024-05-18 14:21:24.510 ERROR (MainThread) [custom_components.aladdin_connect] [API] An error occurred sending command OPEN_DOOR to door Far Garage Door; 400, message='Bad Request', url=URL('https://api.smartgarage.systems/command/devices/F0AD4E14EF14/doors/1')
2024-05-18 14:21:24.510 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [140374338942784] Unexpected exception
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 239, in handle_call_service
response = await hass.services.async_call(
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/core.py", line 2738, in async_call
response_data = await coro
^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/core.py", line 2779, in _execute_service
return await target(service_call)
^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 975, in entity_service_call
single_response = await _handle_entity_call(
^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 1047, in _handle_entity_call
result = await task
^^^^^^^^^^
File "/config/custom_components/aladdin_connect/cover.py", line 107, in async_open_cover
raise HomeAssistantError("Aladdin Connect API failed to open the cover")
homeassistant.exceptions.HomeAssistantError: Aladdin Connect API failed to open the cover
```
</details>

I tried to use
```yaml
service: homeassistant.update_entity
data: {}
target:
  entity_id: cover.main_garage_door
```
but it doesn't update.

Status is however updated upon reload of integration.

I figured this out:

```yaml
service: homeassistant.reload_config_entry
data: {}
target:
  device_id: a3f8a9c8a493b30bdcc0788f26964fde
```
which works as a stop-gap. I'll just have to figure out how to trigger it. I have a camera I can use for my case.

Earlier this week errors were generated because the Genie API responded with "already open" or something similar.

### Reproduction steps

1. open garage door with genie app or button in garage.
2. observe status in integration
3.
...

### Debug logs

```text
NA I believe, but please let me know if you'd like them - Happy to pull all this, but it seems like it's an issue that's been around as there are comments in the forum about it.

https://community.home-assistant.io/t/aladdin-api-changing/676893/39?u=cake1468
```

**Comment by patienttruth** [comment]
Here's an automation that will get this updating. You even get "is closing" while it's in process. Might have to play with the repeat qty, mine too about 25 seconds to get from the close request to "closed".

```yaml
alias: Temp - Update Garage Status on Motion
description: ""
trigger:
  - platform: state
    entity_id:
      - binary_sensor.frigate_lorex_11_shop_2_motion
    to: "on"
condition: []
action:
  - repeat:
      count: 7
      sequence:
        - service: homeassistant.reload_config_entry
          data: {}
          target:
            entity_id:
              - cover.main_garage_door
        - delay:
            hours: 0
            minutes: 0
            seconds: 5
            milliseconds: 0
mode: single
```

**Comment by andyrak** [comment]
Thanks for the info, @patienttruth! I'll take a look at this in this upcoming week and see if I can get the status updates pulled in realtime to avoid the hack.

**Comment by patienttruth** [comment]
> Thanks for the info, @patienttruth! I'll take a look at this in this upcoming week and see if I can get the status updates pulled in realtime to avoid the hack.

You're welcome. Thanks for putting this together! Happy to help if there's anything further I can do, unfortunately my coding skills are minimal. Let me know if I can test or contribute anything further.

**Comment by patienttruth** [comment]
And hey, with the new official integration on deck, this may not even been worth it. In any case, know you're appreciated. 😀

**Comment by patienttruth** [comment]
Closed as not needed. Thank you for the awesome work Andy! I will say I wish the new integration provided the additional sensors that your integration provided. Oh well. It does seem to have solved the updating issue as it updates smoothly.
